import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import Link from "next/link";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <header className="p-10 flex gap-3">
          <Link href="/">Home</Link>
          <Link href="/slide-overs">Slide-Overs</Link>
          <Link href="/not-existing">Not Found</Link>
          <Link href="/captcha">ReCaptcha</Link>
          <Link href="/image-preview">Image Preview</Link>
          <Link href="/calendar">Calendar</Link>
          <Link href="/tree-view">Tree View</Link>
          <Link href="/context-menu">Context Menu</Link>
          <Link href="/editor">Editor Rich Text</Link>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
