import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-10 flex gap-3">
          <Link href="/">Home</Link>
          <Link href="/slide-overs">Slide-Overs</Link>
          <Link href="/not-existing">Not Found</Link>
          <Link href="/captcha">ReCaptcha</Link>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
